import pandas as pd
import numpy as np
import os
import joblib
from sklearn.ensemble import RandomForestClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from scipy.fft import fft, fftfreq

print("Rebuilding AI Brains with Scaled Lifespan Math (1.0 = 100% Health)...")

# The synthetic datasets generated by the Edge Node
training_files = [
    "data/turbine_1_baseline.csv", 
    "data/turbine_2_high_wind.csv",
    "data/turbine_3_blade_pitch_error.csv", 
    "data/turbine_4_aging_bearing.csv"
]

# 1000 rows represents exactly 1 second of 1kHz physics
CHUNK_SIZE = 1000
SAMPLING_RATE = 1000

X_features, y_labels, lstm_sequences = [], [], []
y_lstm_targets = [] 

for file in training_files:
    df = pd.read_csv(file)
    vibration = df['vibration_g'].values
    turbine_sequence = []
    
    # Slicer: Chop the 100-second file into 1-second blocks
    for i in range(0, len(vibration), CHUNK_SIZE):
        chunk = vibration[i:i+CHUNK_SIZE]
        if len(chunk) < CHUNK_SIZE: break
            
        # Feature Extraction: Amplitude (RMS/Peak) and Frequency (FFT)
        rms = np.sqrt(np.mean(chunk**2))
        peak = np.max(np.abs(chunk))
        
        N = len(chunk)
        yf = fft(chunk)
        xf = fftfreq(N, 1/SAMPLING_RATE)
        dominant_freq = xf[np.argmax(np.abs(yf[0:N//2]))]
        
        X_features.append([rms, peak, dominant_freq])
        turbine_sequence.append([rms, peak]) 
        
        # Labeling for Random Forest (0 = Healthy, 1 = Faulty)
        if "blade_pitch" in file: y_labels.append(1)
        elif "aging" in file and i > (len(vibration) * 0.7): y_labels.append(1)
        else: y_labels.append(0)
            
    lstm_sequences.append(turbine_sequence)
    
    # Target Mapping for LSTM (1.0 = 100% Life, 0.0 = 0% Life)
    num_chunks = len(turbine_sequence)
    if "baseline" in file or "high_wind" in file:
        y_lstm_targets.append(np.full(num_chunks, 1.0)) # Stays healthy
    elif "aging" in file:
        y_lstm_targets.append(np.linspace(1.0, 0.0, num_chunks)) # Slow degradation
    else:
        y_lstm_targets.append(np.full(num_chunks, 0.0)) # Instant fault

# 1. Train the Diagnostician (Random Forest)
rf_model = RandomForestClassifier(n_estimators=50, random_state=42)
rf_model.fit(np.array(X_features), np.array(y_labels))
joblib.dump(rf_model, 'turbine_classifier.pkl')

# 2. Train the Forecaster (LSTM Neural Network)
X_lstm = np.array(lstm_sequences)
# Force targets into a strict 3D matrix for Keras
y_lstm = np.array(y_lstm_targets).reshape(X_lstm.shape[0], X_lstm.shape[1], 1) 

lstm_model = Sequential()
lstm_model.add(LSTM(32, input_shape=(X_lstm.shape[1], 2), return_sequences=True))
lstm_model.add(Dense(1))
lstm_model.compile(optimizer='adam', loss='mse')

print("Training LSTM Forecaster (Executing 150 epochs for high precision)...")
lstm_model.fit(X_lstm, y_lstm, epochs=150, verbose=0)
lstm_model.save('predictive_forecaster.keras')

print("SUCCESS: Smart brains locked and loaded.")